import { useState, useEffect } from 'react';

export default function BranchReportPage() {
  const apiUrl = import.meta.env.VITE_API_URL;
  const token = localStorage.getItem('token');

  const [reportData, setReportData] = useState([]);
  const [summary, setSummary] = useState({ total_branches: 0, total_bills: 0, total_discount: 0, total_grand_total: 0 });
  const [shops, setShops] = useState([]);
  
  const [filters, setFilters] = useState({
    from_date: '',
    to_date: '',
    shop_name: ''
  });

  // --- FETCH SHOPS ---
  const fetchShops = async () => {
    try {
      const response = await fetch(`${apiUrl}/shops/`, { headers: { 'Authorization': `Bearer ${token}` } });
      const data = await response.json();
      if (response.ok) {
        if (data.shops) setShops(data.shops);
        else if (Array.isArray(data)) setShops(data);
      }
    } catch (error) { console.error("Failed to fetch shops:", error); }
  };

  // --- FETCH REPORT ---
  const fetchReport = async () => {
    try {
      const queryParams = new URLSearchParams();
      if (filters.from_date) queryParams.append('from_date', filters.from_date);
      if (filters.to_date) queryParams.append('to_date', filters.to_date);
      if (filters.shop_name) queryParams.append('shop_name', filters.shop_name);

      const response = await fetch(`${apiUrl}/reports/branch-wise?${queryParams.toString()}`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      const data = await response.json();
      
      if (response.ok) {
        setReportData(data.data || []);
        setSummary({
          total_branches: data.total_branches || 0,
          total_bills: data.total_bills || 0,
          total_discount: data.total_discount || 0,
          total_grand_total: data.total_grand_total || 0
        });
      }
    } catch (error) { console.error("Error fetching report:", error); }
  };

  // --- EXPORT LOGIC ---
  const handleExportExcel = () => {
    const headers = ["Shop Name", "Bills Count", "Subtotal (₹)", "Discount (₹)", "Grand Total (₹)"];
    const rows = reportData.map(item => [item.shop_name, item.bill_count, item.subtotal, item.discount, item.grand_total]);
    let csvContent = "data:text/csv;charset=utf-8," + headers.join(",") + "\n" + rows.map(e => e.join(",")).join("\n");
    const link = document.createElement("a");
    link.href = encodeURI(csvContent);
    link.download = "Branch_Wise_Report.csv";
    link.click();
  };

  const handleExportPDF = () => window.print();

  // --- WHATSAPP SHARE LOGIC ---
  const handleShareWhatsApp = () => {
    let message = `📊 *Haribiriyani POS Report*\n\n`;
    message += `*Type:* Branch-Wise Sales\n`;
    
    // Date Range
    const fromDate = filters.from_date || 'Today';
    const toDate = filters.to_date || 'Today';
    message += `*Date:* ${fromDate} to ${toDate}\n`;
    
    // Shop
    if (filters.shop_name) {
      message += `*Shop:* ${filters.shop_name}\n`;
    } else {
      message += `*Shop:* All Shops\n`;
    }
    
    message += `\n--------------------------------\n`;
    message += `*Summary:*\n`;
    message += `🏢 Total Branches: ${summary.total_branches}\n`;
    message += `🧾 Total Bills: ${summary.total_bills}\n`;
    message += `🏷️ Total Discount: ₹${summary.total_discount.toFixed(2)}\n`;
    message += `💰 Total Sales: ₹${summary.total_grand_total.toFixed(2)}\n`;
    message += `--------------------------------\n`;
    message += `\nGenerated by Haribiriyani POS`;

    // Encode message for URL
    const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`;
    
    // Open WhatsApp in a new tab
    window.open(whatsappUrl, '_blank');
  };

  // --- LOAD ON MOUNT ---
  useEffect(() => {
    fetchShops();
    fetchReport();
  }, []);

  return (
    <div className="premium-report-container">
      
      {/* Header */}
      <div className="premium-report-header">
        <div>
          <h2>Branch Sales Analytics</h2>
          <p>Performance overview across all branches</p>
        </div>
        <div className="header-actions">
          <button className="export-btn excel" onClick={handleExportExcel}><ExcelIcon /> Excel</button>
          <button className="export-btn pdf" onClick={handleExportPDF}><PdfIcon /> PDF</button>
          {/* NEW WHATSAPP BUTTON */}
          <button className="export-btn whatsapp" onClick={handleShareWhatsApp}>
            <WhatsAppIcon /> WhatsApp
          </button>
        </div>
      </div>

      {/* Filter Bar */}
      <div className="premium-filter-bar">
        <div className="filter-input-group">
          <label>From Date</label>
          <input type="date" className="filter-input" value={filters.from_date} onChange={(e) => setFilters({ ...filters, from_date: e.target.value })} />
        </div>
        <div className="filter-input-group">
          <label>To Date</label>
          <input type="date" className="filter-input" value={filters.to_date} onChange={(e) => setFilters({ ...filters, to_date: e.target.value })} />
        </div>
        <div className="filter-input-group" style={{ flex: '1.5' }}>
          <label>Select Shop</label>
          <select className="filter-input" value={filters.shop_name} onChange={(e) => setFilters({ ...filters, shop_name: e.target.value })}>
            <option value="">All Shops</option>
            {shops.map(shop => <option key={shop.id} value={shop.name}>{shop.name}</option>)}
          </select>
        </div>
        <button className="primary-btn filter-btn" onClick={fetchReport}><FilterIcon /> Generate</button>
      </div>

      {/* Summary KPI Cards */}
      <div className="report-kpi-grid">
        <div className="report-kpi-card orange">
          <div className="kpi-icon-box"><ShopIcon /></div>
          <div className="kpi-text">
            <h4>Total Branches</h4>
            <h2>{summary.total_branches}</h2>
          </div>
        </div>
        <div className="report-kpi-card blue">
          <div className="kpi-icon-box"><BillIcon /></div>
          <div className="kpi-text">
            <h4>Total Bills</h4>
            <h2>{summary.total_bills}</h2>
          </div>
        </div>
        <div className="report-kpi-card green">
          <div className="kpi-icon-box"><DiscountIcon /></div>
          <div className="kpi-text">
            <h4>Total Discount</h4>
            <h2>₹{summary.total_discount.toFixed(2)}</h2>
          </div>
        </div>
        <div className="report-kpi-card red">
          <div className="kpi-icon-box"><SalesIcon /></div>
          <div className="kpi-text">
            <h4>Total Sales</h4>
            <h2>₹{summary.total_grand_total.toFixed(2)}</h2>
          </div>
        </div>
      </div>

      {/* Report Table */}
      <div className="report-table-card">
        <div className="table-wrapper">
          <table className="modern-data-table">
            <thead>
              <tr>
                <th>Shop Name</th>
                <th>Bills Count</th>
                <th>Subtotal</th>
                <th>Discount</th>
                <th>Grand Total</th>
              </tr>
            </thead>
            <tbody>
              {reportData.length === 0 ? (
                <tr><td colSpan="5" style={{textAlign: 'center', color: '#64748b', padding: '40px'}}>No data available for selected filters</td></tr>
              ) : (
                reportData.map((item, index) => (
                  <tr key={index}>
                    <td><div className="table-name-cell">{item.shop_name}</div></td>
                    <td>{item.bill_count}</td>
                    <td>₹{item.subtotal.toFixed(2)}</td>
                    <td>₹{item.discount.toFixed(2)}</td>
                    <td className="amount-cell">₹{item.grand_total.toFixed(2)}</td>
                  </tr>
                ))
              )}
            </tbody>
            {reportData.length > 0 && (
              <tfoot>
                <tr>
                  <td style={{ fontWeight: '800', color: '#1e293b', fontSize: '1rem' }}>Grand Total</td>
                  <td style={{ fontWeight: '800', color: '#1e293b', fontSize: '1rem' }}>{summary.total_bills}</td>
                  <td style={{ fontWeight: '800', color: '#1e293b', fontSize: '1rem' }}>₹{summary.total_subtotal ? summary.total_subtotal.toFixed(2) : '0.00'}</td>
                  <td style={{ fontWeight: '800', color: '#16a34a', fontSize: '1rem' }}>₹{summary.total_discount.toFixed(2)}</td>
                  <td style={{ fontWeight: '800', color: '#b91c1c', fontSize: '1.05rem' }}>₹{summary.total_grand_total.toFixed(2)}</td>
                </tr>
              </tfoot>
            )}
          </table>
        </div>
      </div>

    </div>
  );
}

/* SVG Icons */
const ExcelIcon = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="12" y1="18" x2="12" y2="12"/><line x1="9" y1="15" x2="15" y2="15"/></svg>;
const PdfIcon = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><path d="M9 13h6"/><path d="M9 17h6"/></svg>;
const FilterIcon = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/></svg>;
const ShopIcon = () => <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 9l1-5h16l1 5M3 9v11a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V9M3 9h18M8 13h8"/></svg>;
const BillIcon = () => <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>;
const DiscountIcon = () => <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="19" y1="5" x2="5" y2="19"/><circle cx="6.5" cy="6.5" r="2.5"/><circle cx="17.5" cy="17.5" r="2.5"/></svg>;
const SalesIcon = () => <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>;
// Added WhatsApp SVG Icon
const WhatsAppIcon = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.149-.197.297-.767.967-.94 1.165-.173.198-.347.223-.644.074-.297-.149-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51l-.57-.01c-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.981.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.885-9.885 9.885M20.52 3.449C18.424 1.353 15.622.001 12.503 0 5.722 0 .093 5.621.09 12.4c0 2.185.571 4.318 1.655 6.205L0 24l6.515-1.708a12.4 12.4 0 005.982 1.523h.005c6.781 0 12.41-5.621 12.412-12.4 0-3.317-1.29-6.432-3.636-8.783"/></svg>;