export default function DashboardPage() {
  // Top KPI Data
  const stats = [
    { title: 'Daily Sales', value: '₹45,200', change: '+12%', icon: SalesIcon, color: 'red' },
    { title: 'Total Bills', value: '128', change: '+8%', icon: OrdersIcon, color: 'blue' },
    { title: 'Avg Order Value', value: '₹353', change: '+2%', icon: AvgIcon, color: 'green' },
  ];

  // Shop Sales Breakdown Data
  const shopSales = [
    { name: 'Hari Vegetables', amount: '₹12,500', percentage: 60, color: '#16a34a' },
    { name: 'Hari Broilers', amount: '₹25,700', percentage: 85, color: '#dc2626' },
    { name: 'Hari Eggs', amount: '₹7,000', percentage: 40, color: '#f59e0b' },
  ];

  // Payment Methods Data
  const paymentMethods = [
    { name: 'Cash', amount: '₹25,000', percentage: 55, color: '#16a34a' },
    { name: 'Card', amount: '₹12,000', percentage: 27, color: '#2563eb' },
    { name: 'GPay', amount: '₹6,000', percentage: 13, color: '#dc2626' },
    { name: 'Other', amount: '₹2,200', percentage: 5, color: '#f59e0b' },
  ];

  // Calculate conic gradient for Payment Donut Chart
  let payGradient = 'conic-gradient(';
  let payStart = 0;
  paymentMethods.forEach(pm => {
    payGradient += `${pm.color} ${payStart}% ${payStart + pm.percentage}%, `;
    payStart += pm.percentage;
  });
  payGradient += `#f1f5f9 ${payStart}% 100%)`;

  // Top 5 Selling Items Data
  const topItems = [
    { rank: 1, name: 'Whole Chicken', shop: 'Hari Broilers', qty: '45 kg', amount: '₹8,100' },
    { rank: 2, name: 'Tomatoes', shop: 'Hari Vegetables', qty: '85 kg', amount: '₹3,400' },
    { rank: 3, name: 'Chicken Breast', shop: 'Hari Broilers', qty: '20 kg', amount: '₹4,400' },
    { rank: 4, name: 'Onions', shop: 'Hari Vegetables', qty: '60 kg', amount: '₹3,000' },
    { rank: 5, name: 'Farm Eggs', shop: 'Hari Eggs', qty: '150 pcs', amount: '₹900' },
  ];

  return (
    <div className="dash-container">
      
      {/* Compact KPI Cards Row */}
      <div className="dash-kpi-row">
        {stats.map((stat, index) => {
          const Icon = stat.icon;
          return (
            <div className="dash-kpi-card" key={index}>
              <div className={`dash-kpi-icon ${stat.color}`}>
                <Icon />
              </div>
              <div className="dash-kpi-text">
                <h4>{stat.title}</h4>
                <h2>{stat.value}</h2>
                <span className={`dash-kpi-change ${stat.color}`}>{stat.change} vs yesterday</span>
              </div>
            </div>
          );
        })}
      </div>

      {/* Analytics Row (Shop Sales + Payment Methods) */}
      <div className="dash-main-row">
        
        {/* Shop Sales Breakdown */}
        <div className="dash-card">
          <div className="dash-card-header">
            <h3>Shop Sales Today</h3>
            <p>Revenue generated by each shop</p>
          </div>
          <div className="shop-sales-list">
            {shopSales.map((shop, index) => (
              <div className="shop-sale-item" key={index}>
                <div className="shop-sale-top">
                  <h5>{shop.name}</h5>
                  <span className="shop-sale-amount">{shop.amount}</span>
                </div>
                <div className="shop-progress-track">
                  <div className="shop-progress-fill" style={{ width: `${shop.percentage}%`, background: shop.color }}></div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Payment Methods Donut Chart */}
        <div className="dash-card">
          <div className="dash-card-header">
            <h3>Payment Methods Today</h3>
            <p>Breakdown by transaction type</p>
          </div>
          
          <div className="pay-chart-layout">
            <div className="pay-donut-container">
              <div className="pay-donut" style={{ background: payGradient }}>
                <div className="pay-donut-inner">
                  <h2>100%</h2>
                  <p>Transactions</p>
                </div>
              </div>
            </div>

            <div className="pay-legend">
              {paymentMethods.map((pm, index) => (
                <div className="pay-legend-item" key={index}>
                  <span className="legend-dot" style={{ background: pm.color }}></span>
                  <span className="legend-name">{pm.name}</span>
                  <span className="legend-value">{pm.amount}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

      </div>

      {/* Top 5 Selling Items Table */}
      <div className="dash-card">
        <div className="dash-card-header">
          <h3>Top 5 Selling Items</h3>
          <p>Best performing products across all shops today</p>
        </div>
        <div className="table-wrapper">
          <table className="modern-data-table compact">
            <thead>
              <tr>
                <th>Rank</th>
                <th>Item Name</th>
                <th>Shop</th>
                <th>Qty Sold</th>
                <th>Revenue</th>
              </tr>
            </thead>
            <tbody>
              {topItems.map((item) => (
                <tr key={item.rank}>
                  <td>
                    <div className={`rank-badge rank-${item.rank}`}>
                      {item.rank}
                    </div>
                  </td>
                  <td><div className="table-name-cell">{item.name}</div></td>
                  <td>{item.shop}</td>
                  <td>{item.qty}</td>
                  <td className="amount-cell">{item.amount}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
}

/* Compact SVG Icons */
const SalesIcon = () => <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>;
const OrdersIcon = () => <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9 11H3v10h6V11zM21 3h-6v18h6V3zM15 9H9v12h6V9z"/></svg>;
const AvgIcon = () => <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/></svg>;