import { useState, useEffect } from 'react';

export default function DashboardPage() {
  const apiUrl = import.meta.env.VITE_API_URL;
  const token = localStorage.getItem('token');

  const [dashboardData, setDashboardData] = useState(null);

  // --- FETCH DASHBOARD DATA ---
  useEffect(() => {
    const fetchDashboard = async () => {
      try {
        const response = await fetch(`${apiUrl}/reports/dashboard`, {
          headers: { 'Authorization': `Bearer ${token}` }
        });
        const data = await response.json();
        if (response.ok) {
          setDashboardData(data);
        } else {
          console.error("Failed to fetch dashboard data");
        }
      } catch (error) {
        console.error("Error fetching dashboard data:", error);
      }
    };

    fetchDashboard();
  }, [token, apiUrl]);

  // --- CALCULATIONS & DATA MAPPING ---
  
  // 1. Summary Stats
  const summary = dashboardData?.summary || {};
  const stats = [
    { title: 'Total Sales', value: `₹${(summary.total_sales || 0).toFixed(2)}`, icon: SalesIcon, color: 'red' },
    { title: 'Total Bills', value: summary.total_bills || 0, icon: OrdersIcon, color: 'blue' },
    { title: 'Avg Order Value', value: `₹${(summary.average_bill_value || 0).toFixed(2)}`, icon: AvgIcon, color: 'green' },
  ];

  // 2. Shop Sales (Calculate % relative to max shop sale for progress bar)
  const rawShopSales = dashboardData?.shop_sales || [];
  const maxShopSale = rawShopSales.length > 0 ? Math.max(...rawShopSales.map(s => s.total_sales)) : 1;
  
  const shopColors = ['#16a34a', '#dc2626', '#f59e0b', '#2563eb', '#7c3aed'];
  const shopSales = rawShopSales.map((shop, index) => ({
    name: shop.shop_name,
    amount: `₹${shop.total_sales.toFixed(2)}`,
    percentage: Math.round((shop.total_sales / maxShopSale) * 100),
    color: shopColors[index % shopColors.length]
  }));

  // 3. Payment Methods (Calculate % for donut chart)
  const rawPayments = dashboardData?.payment_methods || {};
  const paymentColors = {
    Cash: '#16a34a',
    Card: '#2563eb',
    GPay: '#dc2626',
    Other: '#f59e0b'
  };

  const totalPaymentAmount = Object.values(rawPayments).reduce((acc, pm) => acc + (pm.total_amount || 0), 0);
  
  const paymentMethods = Object.keys(rawPayments).map(name => {
    const pmData = rawPayments[name] || {};
    const amount = pmData.total_amount || 0;
    return {
      name,
      amount: `₹${amount.toFixed(2)}`,
      percentage: totalPaymentAmount > 0 ? Math.round((amount / totalPaymentAmount) * 100) : 0,
      color: paymentColors[name] || '#94a3b8'
    };
  });

  // Calculate conic gradient for Payment Donut Chart
  let payGradient = 'conic-gradient(';
  let payStart = 0;
  let hasPayments = false;
  
  paymentMethods.forEach(pm => {
    if (pm.percentage > 0) {
      hasPayments = true;
      payGradient += `${pm.color} ${payStart}% ${payStart + pm.percentage}%, `;
      payStart += pm.percentage;
    }
  });
  
  payGradient += `#f1f5f9 ${payStart}% 100%)`;
  
  // Fallback if no payments exist
  if (!hasPayments) {
    payGradient = 'conic-gradient(#e2e8f0 0% 100%)';
  }

  // 4. Top 5 Selling Items
  const rawTopItems = dashboardData?.top_selling_items || [];
  const topItems = rawTopItems.map((item, index) => ({
    rank: index + 1,
    name: item.product_name,
    qty: `${item.total_quantity} ${item.unit || ''}`,
    amount: `₹${item.total_amount.toFixed(2)}`
  }));

  return (
    <div className="dash-container">
      
      {/* Compact KPI Cards Row */}
      <div className="dash-kpi-row">
        {stats.map((stat, index) => {
          const Icon = stat.icon;
          return (
            <div className="dash-kpi-card" key={index}>
              <div className={`dash-kpi-icon ${stat.color}`}>
                <Icon />
              </div>
              <div className="dash-kpi-text">
                <h4>{stat.title}</h4>
                <h2>{stat.value}</h2>
                {/* Removed fake "+12% vs yesterday" since API doesn't provide historical data */}
              </div>
            </div>
          );
        })}
      </div>

      {/* Analytics Row (Shop Sales + Payment Methods) */}
      <div className="dash-main-row">
        
        {/* Shop Sales Breakdown */}
        <div className="dash-card">
          <div className="dash-card-header">
            <h3>Shop Sales Today</h3>
            <p>Revenue generated by each shop</p>
          </div>
          <div className="shop-sales-list">
            {shopSales.length === 0 ? (
              <p style={{ color: '#64748b', fontSize: '0.9rem', textAlign: 'center' }}>No sales data available</p>
            ) : (
              shopSales.map((shop, index) => (
                <div className="shop-sale-item" key={index}>
                  <div className="shop-sale-top">
                    <h5>{shop.name}</h5>
                    <span className="shop-sale-amount">{shop.amount}</span>
                  </div>
                  <div className="shop-progress-track">
                    <div className="shop-progress-fill" style={{ width: `${shop.percentage}%`, background: shop.color }}></div>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Payment Methods Donut Chart */}
        <div className="dash-card">
          <div className="dash-card-header">
            <h3>Payment Methods Today</h3>
            <p>Breakdown by transaction type</p>
          </div>
          
          <div className="pay-chart-layout">
            <div className="pay-donut-container">
              <div className="pay-donut" style={{ background: payGradient }}>
                <div className="pay-donut-inner">
                  <h2>100%</h2>
                  <p>Transactions</p>
                </div>
              </div>
            </div>

            <div className="pay-legend">
              {paymentMethods.map((pm, index) => (
                <div className="pay-legend-item" key={index}>
                  <span className="legend-dot" style={{ background: pm.color }}></span>
                  <span className="legend-name">{pm.name}</span>
                  <span className="legend-value">{pm.amount}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

      </div>

      {/* Top 5 Selling Items Table */}
      <div className="dash-card">
        <div className="dash-card-header">
          <h3>Top 5 Selling Items</h3>
          <p>Best performing products across all shops today</p>
        </div>
        <div className="table-wrapper">
          <table className="modern-data-table compact">
            <thead>
              <tr>
                <th>Rank</th>
                <th>Item Name</th>
                <th>Qty Sold</th>
                <th>Revenue</th>
              </tr>
            </thead>
            <tbody>
              {topItems.length === 0 ? (
                <tr><td colSpan="4" style={{textAlign: 'center', color: '#64748b', padding: '20px'}}>No items sold yet</td></tr>
              ) : (
                topItems.map((item) => (
                  <tr key={item.rank}>
                    <td>
                      <div className={`rank-badge rank-${item.rank}`}>
                        {item.rank}
                      </div>
                    </td>
                    <td><div className="table-name-cell">{item.name}</div></td>
                    <td>{item.qty}</td>
                    <td className="amount-cell">{item.amount}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
}

/* Compact SVG Icons */
const SalesIcon = () => <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>;
const OrdersIcon = () => <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9 11H3v10h6V11zM21 3h-6v18h6V3zM15 9H9v12h6V9z"/></svg>;
const AvgIcon = () => <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/></svg>;